"""empty message

Revision ID: 90eebc17c5e4
Revises: 044c5b54760c
Create Date: 2024-06-20 23:35:35.993027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90eebc17c5e4'
down_revision = '044c5b54760c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('subCategory', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('video', sa.String(), nullable=True),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], name=op.f('fk_episodes_show_id_shows')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('episodes')
    op.drop_table('shows')
    # ### end Alembic commands ###
